export type AirportCatalogItem = {
  code: string;
  text: string;
  aliases: string[];
};

/**
 * Canonical airport catalog used by parser and mapper boundaries.
 *
 * Keep airport code/text updates here so resolver logic stays small and future
 * airport additions do not touch Telegram or Playwright automation flows.
 *
 * List familiar city/airport spellings explicitly for both model prompts and
 * local lookup. Accented names ground the model; joined spellings cover common
 * chat input. Case/NFD variants are handled by the resolver, not extra aliases.
 * Preserve canonical code/text pairs; avoid ambiguous abbreviations or inferred
 * nearby-airport mappings. Run `pnpm test:airports` after catalog edits.
 */
export const AIRPORT_CATALOG = [
  {
    code: 'VCA',
    text: 'Can Tho International Airport (VCA)',
    aliases: [
      'vca',
      'can tho',
      'cantho',
      'tra noc',
      'tra noc airport',
      'Cần Thơ',
      'Trà Nóc',
      'tranoc',
    ],
  },
  {
    code: 'DLI',
    text: 'Lien Khuong International Airport (DLI)',
    aliases: [
      'dli',
      'da lat',
      'dalat',
      'lien khuong',
      'lam dong',
      'Đà Lạt',
      'Liên Khương',
      'Lâm Đồng',
      'lienkhuong',
      'lamdong',
    ],
  },
  {
    code: 'DAD',
    text: 'Da Nang International Airport (DAD)',
    aliases: [
      'dad',
      'da nang',
      'danang',
      'dn',
      'Đà Nẵng',
    ],
  },
  {
    code: 'HPH',
    text: 'Cat Bi International Airport (HPH)',
    aliases: [
      'hph',
      'hai phong',
      'haiphong',
      'cat bi',
      'Hải Phòng',
      'Cát Bi',
      'catbi',
    ],
  },
  {
    code: 'VDO',
    text: 'Van Don International Airport (VDO)',
    aliases: [
      'vdo',
      'van don',
      'quang ninh',
      'Vân Đồn',
      'Quảng Ninh',
      'vandon',
      'quangninh',
    ],
  },
  {
    code: 'HAN',
    text: 'Sân bay Nội Bài (HAN)',
    aliases: [
      'ha noi',
      'hanoi',
      'noi bai',
      'han',
      'hn',
      'Hà Nội',
      'Nội Bài',
      'noibai',
    ],
  },
  {
    code: 'SGN',
    text: 'Sân bay Tân Sơn Nhất (SGN)',
    aliases: [
      'sai gon',
      'saigon',
      'ho chi minh',
      'hcm',
      'tphcm',
      'sgn',
      'tan son nhat',
      'Sài Gòn',
      'Hồ Chí Minh',
      'Tân Sơn Nhất',
      'hochiminh',
      'hochiminh city',
      'ho chi minh city',
      'tp hcm',
      'tp.hcm',
      'tp. hcm',
      'tphochiminh',
      'tansonnhat',
    ],
  },
  {
    code: 'HUI',
    text: 'Phu Bai International Airport (HUI)',
    aliases: [
      'hui',
      'hue',
      'phu bai',
      'thua thien hue',
      'Huế',
      'Phú Bài',
      'Thừa Thiên Huế',
      'phubai',
      'thuathienhue',
    ],
  },
  {
    code: 'CXR',
    text: 'Cam Ranh International Airport (CXR)',
    aliases: [
      'cxr',
      'nha trang',
      'cam ranh',
      'cam ranh air base',
      'nhatrang',
      'camranh',
    ],
  },
  {
    code: 'PQC',
    text: 'Phu Quoc International Airport (PQC)',
    aliases: [
      'pqc',
      'phu quoc',
      'duong dong',
      'Phú Quốc',
      'Dương Đông',
      'phuquoc',
      'duongdong',
    ],
  },
  {
    code: 'VII',
    text: 'Vinh International Airport (VII)',
    aliases: [
      'vii',
      'vinh',
      'nghe an',
      'Nghệ An',
      'nghean',
    ],
  },
  {
    code: 'BMV',
    text: 'Buon Ma Thuot Airport (BMV)',
    aliases: [
      'bmv',
      'buon ma thuot',
      'ban me thuot',
      'dak lak',
      'Buôn Ma Thuột',
      'Ban Mê Thuột',
      'Đắk Lắk',
      'buonmathuot',
      'banmethuot',
      'daklak',
    ],
  },
  {
    code: 'TBB',
    text: 'Tuy Hoa Airport (TBB)',
    aliases: [
      'tbb',
      'tuy hoa',
      'phu yen',
      'Tuy Hòa',
      'Phú Yên',
      'tuyhoa',
      'phuyen',
    ],
  },
  {
    code: 'CAH',
    text: 'Ca Mau Airport (CAH)',
    aliases: [
      'cah',
      'ca mau',
      'Cà Mau',
      'camau',
    ],
  },
  {
    code: 'VCL',
    text: 'Chu Lai Airport (VCL)',
    aliases: [
      'vcl',
      'chu lai',
      'quang nam',
      'tam ky',
      'Quảng Nam',
      'Tam Kỳ',
      'chulai',
      'quangnam',
      'tamky',
    ],
  },
  {
    code: 'VCS',
    text: 'Con Dao Airport (VCS)',
    aliases: [
      'vcs',
      'con dao',
      'con son',
      'Côn Đảo',
      'Côn Sơn',
      'condao',
      'conson',
    ],
  },
  {
    code: 'VTG',
    text: 'Vung Tau Airport (VTG)',
    aliases: [
      'vtg',
      'vung tau',
      'Vũng Tàu',
      'vungtau',
    ],
  },
  {
    code: 'DIN',
    text: 'Dien Bien Airport (DIN)',
    aliases: [
      'din',
      'dien bien',
      'dien bien phu',
      'Điện Biên',
      'Điện Biên Phủ',
      'dienbien',
      'dienbienphu',
    ],
  },
  {
    code: 'VDH',
    text: 'Dong Hoi Airport (VDH)',
    aliases: [
      'vdh',
      'dong hoi',
      'quang binh',
      'Đồng Hới',
      'Quảng Bình',
      'donghoi',
      'quangbinh',
    ],
  },
  {
    code: 'PXU',
    text: 'Pleiku Airport (PXU)',
    aliases: [
      'pxu',
      'pleiku',
      'plei ku',
      'gia lai',
      'gialai',
    ],
  },
  {
    code: 'UIH',
    text: 'Phu Cat Airport (UIH)',
    aliases: [
      'uih',
      'quy nhon',
      'qui nhon',
      'phu cat',
      'binh dinh',
      'Quy Nhơn',
      'Qui Nhơn',
      'Phù Cát',
      'Bình Định',
      'quynhon',
      'quinhon',
      'phucat',
      'binhdinh',
    ],
  },
  {
    code: 'VKG',
    text: 'Rach Gia Airport (VKG)',
    aliases: [
      'vkg',
      'rach gia',
      'kien giang',
      'Rạch Giá',
      'Kiên Giang',
      'rachgia',
      'kiengiang',
    ],
  },
  {
    code: 'THD',
    text: 'Tho Xuan Airport (THD)',
    aliases: [
      'thd',
      'tho xuan',
      'thanh hoa',
      'Thọ Xuân',
      'Thanh Hóa',
      'thoxuan',
      'thanhhoa',
    ],
  },
  {
    code: 'PHA',
    text: 'Phan Rang Air Base (PHA)',
    aliases: [
      'pha',
      'phan rang',
      'phan rang thap cham',
      'ninh thuan',
      'Phan Rang Tháp Chàm',
      'Ninh Thuận',
      'phanrang',
      'phanrangthapcham',
      'ninhthuan',
    ],
  },
  {
    code: 'LTH',
    text: 'Long Thanh International Airport (LTH)',
    aliases: [
      'lth',
      'long thanh',
      'dong nai',
      'Long Thành',
      'Đồng Nai',
      'longthanh',
      'dongnai',
    ],
  },
] as const satisfies readonly AirportCatalogItem[];
